out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: pcqm4m
dataset:
  format: OGB
  name: PCQM4Mv2-full
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_shared: True
  edge_encoder_name: Bond+RWSE
  edge_encoder_bn: False
  rings: False
  rings_max_length: 6
  rings_coalesce_edges: False
posenc_RWSE:
  enable: True
  precompute: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 10
model:
  type: GPSModel
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: None+CSA
  layers: 16
  n_heads: 16
  dim_hidden: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0001
  max_epoch: 150
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
