out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC_seeds
  entity: emmanuel-jehanno
  name: (QK+E)*(V+E)_DptConn_VerySmall_vf
  dir: /gpfswork/rech/tbr/ump88gx/EJ_GraphGPS/GraphGPS/wandb/
dataset:
  dir: /gpfswork/rech/tbr/ump88gx/EJ_GraphGPS/GraphGPS/datasets/
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 14
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge+RWSE
  edge_encoder_num_types: 4
  edge_encoder_bn: False
  rings: True
  rings_max_length: 18
  rings_coalesce_edges: True
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,20)
  model: Linear
  dim_pe: 14
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: None+GraphiT  # CustomGatedGCN+Performer
  layers: 10
  n_heads: 1
  dim_hidden: 16  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
  #mask_type: adj
  layer_args:
    - QK_op: multiplication
    - KE_op: addition
    - edge_out_dim: null
    - dropout_lvl: connections
    - VE_op: addition
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 16  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50