out_dir: results
metric_best: mrr
num_workers: 4
wandb:
  use: True
  project: pcqm4m-contact
  entity: emmanuel-jehanno
  name: (QK+E)*(V+E)_multi_DptConn
  dir: /gpfswork/rech/tbr/ump88gx/EJ_GraphGPS/GraphGPS/wandb/PCQM4Mv2Contact
dataset:
  dir: /gpfswork/rech/tbr/ump88gx/EJ_GraphGPS/GraphGPS/datasets
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond+RWSE
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
gt:
  layer_type: None+GraphiT
  layers: 10
  n_heads: 4
  dim_hidden: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
  layer_args:
    - QK_op: multiplication
    - KE_op: addition
    - edge_out_dim: null
    - dropout_lvl: connections
    - VE_op: addition
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_post_mp: 1
  dim_inner: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
#optim:
#  batch_accumulation: 1
#  optimizer: adamW
#  weight_decay: 0.0
#  base_lr: 0.0003
#  max_epoch: 200
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 10
#  min_lr: 1e-5
