out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: pcqm4m-subset
  entity: emmanuel-jehanno
  name: (QK+E_mono)*V_DptConn
  dir: /gpfswork/rech/tbr/ump88gx/EJ_GraphGPS/GraphGPS/wandb/
dataset:
  dir: /gpfswork/rech/tbr/ump88gx/EJ_GraphGPS/GraphGPS/datasets
  format: OGB
  name: PCQM4Mv2-subset
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond+RWSE
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  precompute: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: None+GraphiT
  layers: 5
  n_heads: 4
  dim_hidden: 304  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
  layer_args:
    - QK_op: multiplication
    - KE_op: addition
    - edge_out_dim: 1
    - dropout_lvl: connections
    - VE_op: null
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 304  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
