out_dir: results
metric_best: f1
wandb:
  use: True
  project: Pascal
  entity: emmanuel-jehanno
  name: (QK+E)*(V+E)_multi_DptConn
dataset:
  dir: /scratch2/clear/ejehanno/datasets
  format: PyG-VOCSuperpixels
  name: edge_wt_only_coord  # Alternative: edge_wt_region_boundary
  slic_compactness: 10
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: VOCNode+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: VOCEdge+RWSE
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: weighted_cross_entropy
gt:
  layer_type: None+GraphiT
  layers: 4
  n_heads: 8
  dim_hidden: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 500
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5